In [2]:
from google.colab import files
uploaded = files.upload()

Saving delivery_time.csv to delivery_time.csv
Saving school_data.csv to school_data.csv
Saving school_data_social.csv to school_data_social.csv
Saving school_data_science.csv to school_data_science.csv
Saving type1_data2.csv to type1_data2.csv
Saving type1_data1.csv to type1_data1.csv

# Section 1 필터링, 최솟값, 중앙값

1. 'f5'칼럼이 0이 아닌 데이터(행)를 구하시오.
2. 앞에서 구한 데이터에 'views'컬럼 결측치를 'views' 컬럼의 최솟값으로 채워주세요.
3. 그리고 'views'컬럼의 중앙값을 계산해 정수로 구하시오.

In [2]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/refs/heads/main/part1/ch3/type1_data1.csv")
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [3]:
#0이 아닌 데이터행
cond = df['f5'] !=0
df = df[cond]

#views 컬럼 결측치를 views 컬럼 최솟값으로 대치
df['views'].fillna(df['views'].min(), inplace=True)
df

#views 컬럼의 중앙값
print(int(df['views'].median()))

5924

<ipython-input-3-98c1eb7dc6c2>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['views'].fillna(df['views'].min(), inplace=True)
<ipython-input-3-98c1eb7dc6c2>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['views'].fillna(df['views'].min(), inplace=True)

# Section 2 카테고리, 인덱스, 문자열
1.'subscribed'칼럼에서 가장 빈도수가 많은 날짜를 구하시오.
2. 앞에서 구한 날짜의 일(day)값을 정수로 구하시오

In [4]:
df

        id    age city    f1  f2    f3    f4         f5  subscribed    views
0     id01    2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16   6820.0
1     id02    9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12   2534.0
2     id03   27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16   7312.0
3     id04   75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21    493.0
4     id05   24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07   1338.0
..     ...    ...  ...   ...  ..   ...   ...        ...         ...      ...
97    id97  100.0   경기   NaN   0  gold  INFP  67.886373  2024-03-18   6687.0
98    id98   39.0   경기  58.0   2   NaN  INFP  98.429899  2024-10-02    865.0
99    id99    1.0   경기  47.0   0  gold  ESFJ  97.381034  2024-12-02   6090.0
100  id100   47.0   경기  53.0   0   vip  ESFP  33.308999  2024-02-21  15535.0
101   id68   35.0   경기  45.0   2  gold  ISFP  67.886373  2024-07-29   8599.0

[102 rows x 10 columns]

In [5]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [6]:
#Q. subscribed 컬럼에서 가장 빈도수가 많은 날짜를 구하시오
df = df['subscribed'].value_counts()
int(df.index[0][-2:])

17

# Section 3 파생변수, 정렬, 인덱싱

1. 결측치가 있는 데이터(행)를 제거하시오.
2. 'views'컬럼을 'f1'칼럼으로 나눈 값을 새로운 컬럼으로 추가하시오.
3. 새로운 컬럼 값 중 가장 큰 값을 가진 행의 age를 정수로 구하시오.

In [7]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv("type1_data1.csv")

In [8]:
#결측치가 있는 데이터(행) 제거
df.dropna()

#새로운 칼럼 추가
df['new'] = df['views']/df['f1']

#새로운 칼럼 값 중 가장 큰 값 찾기
df = df.sort_values('new', ascending = False)

#가장 큰 행의 age를 정수로 구하기
int(df.iloc[0,1])

22

In [9]:
#2번째 풀이
int(df.loc[df['new'].idxmax(),'age'])

22

# Section 4 값 변경, 정렬, 합계

1. 'views' 컬럼의 결측 데이터를 0으로 대체하시오.
2. 'views' 컬럼에서 상위 10번째 값을 구하시오.
3. 'views' 컬럼에서 상위 10개의 값을 상위 10번째 값으로 대체하시오.
4. 'views' 컬럼의 전체 합을 정수로 구하시오.

In [10]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('type1_data1.csv')

#결측 데이터 0으로 대치
df['views'].fillna(0, inplace= True)

#상위 10번째 값
df = df.sort_values('views', ascending = False)
# views_min = df.iloc[:10]['views'].min()
# df.iloc[:10,-1] = views_min

df.iloc[:10, -1] = df.iloc[9,-1]

#sum
int(df['views'].sum())

<ipython-input-10-cf053b2eebd8>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['views'].fillna(0, inplace= True)

652812

In [11]:
import pandas as pd
df = pd.read_csv('type1_data1.csv')

#결측 데이터 대치
df.fillna(0, inplace = True)

#상위 10번째 값
value = df['views'].nlargest(10).iloc[-1]

#대치
cond = df['views'] >= value

df.loc[cond, 'views'] = value

#sum

int(df['views'].sum())

652812

# Section 5 문자열 슬라이싱, 파생변수, 평균값

1. 'f4' 컬럼 데이터에 'FJ'가 포함된 데이터를 찾으시오.
2. 찾은 데이터 중에서 'f2' 컬럼의 평균값을 구하시오. (반올림 후 소수 둘째 자리까지 계산)

In [12]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('type1_data1.csv')

#FJ가 포함된 데이터 찾기
cond = df['f4'].str.contains('FJ')

#찾은 데이터 중에서 'f2'컬럼의 평균값구하기
df = df[cond]

#소숫점 둘째자리로 올려서 계산
round(df['f2'].mean(),2)

np.float64(0.61)

In [13]:
#2번째 풀이
import pandas as pd
df = pd.read_csv('type1_data1.csv')

df['new'] = df['f4'].str[2:4]

cond = df['new'] =='FJ'
df = df[cond]

print(round(df['f2'].mean(),2))

0.61

# Section 6 필터링, 분산

1. 'f3'컬럼이 gold이면서 'f2'컬럼이 2인 데이터를 찾으시오.
2. 찾은 데이터에서 'f1' 컬ㄹ럼의 분산을 구하시오. (반올림 후 소수 둘째 자리까지 계산)

In [14]:
import pandas as pd
df = pd.read_csv('type1_data1.csv')

#f3 gold f2 2
cond1 = df['f3'] =='gold'
cond2 = df['f2'] ==2

df = df[cond1 & cond2]

#f1컬럼의 분산

print(round(df['f1'].var(),2))

235.43

# Section 7 값 변경(연산), 필터링 절댓값

1. 모든 나이(age)에 1을 더하시오.
2. 20대의 'views' 평균과 30대의 'views' 평균의 차이의 절댓값을 구하시오. (반올림 후 소수 둘째 자리까지 계산)

In [15]:
import pandas as pd
df = pd.read_csv("type1_data1.csv")


#모든 age에 1 더하기
df['age'] = df['age'] + 1

#20대의 views 평균과 30대의 views 평균의 차이의 절댓값
#20대의 views 평균
cond20 = (df['age'] <30) & (df['age'] >=20)
cond30 = (df['age'] <40) & (df['age'] >=30)

print(round(abs(df[cond20]['views'].mean()-df[cond30]['views'].mean()),2))

263.13

# Section 8 시계열 데이터, 필터링, 데이터 개수

1. 'subscribed' 컬럼이 2024년 2월인 데이터를 찾으시오.
2. 위에서 찾은 데이터 중 'f3'컬럼이 gold인 데이터의 개수를 구하시오.

In [16]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('type1_data1.csv')

#to_datetime
df['subscribed'] = pd.to_datetime(df['subscribed'])

#파생변수 생성(연과 월)
df['year'] = df['subscribed'].dt.year
df['month'] = df['subscribed'].dt.month

#2024년 2월
cond1 = df['year'] == 2024
cond2 = df['month'] == 2

df = df[cond1 & cond2]
df

cond3 = df['f3'] =='gold'
#데이터 개수
len(df[cond3])

5

# Section 9 필터링, 카테고리, 최빈값
1. views 칼럼 값이 1000이하인 데이터(결측치 제외)를 찾으시오.
2. 앞에서 구한 데이터 중 'f4'컬럼의 최빈값을 구하시오

In [17]:
import pandas as pd
df = pd.read_csv('type1_data1.csv')

#결측치 제거
df['views'] = df['views'].dropna()

#views 컬럼 값이 1000이하인 데이터
cond = df['views'] <= 1000


df= df[cond]

#f4컬럼의 최빈값
df['f4'].mode()[0]

#mode()는 sum(), mean()과 같은 다른 집계함수와 달리 Series 형태로 반환한다.

'ISFJ'

# Section 10 그룹핑, 최댓값, 정렬
1. 결측치가 있는 행을 삭제하시오.
2. 결측치가 삭제된 데이터를 사용하여 지역별(city) 평균을 계산하시오.
3. 앞에서 계산한 지역별 평균 데이터에서 'f2'컬럼 값이 가장 큰 지역을 구하시오.

In [18]:
import pandas as pd
df = pd.read_csv('type1_data1.csv')

#결측제 제거
df = df.dropna()

#지역별 평균
df = df.groupby(['city']).mean(numeric_only=1)

#f2 칼럼이 가장 큰 지역
df.sort_values("f2", ascending = False).index[0]

# df['f2'].idxmax() 이렇게 해도됨. grouping의 index가 city이기에 가능

'서울'

# Section 11 슬라이싱, 사분위수, 결측지 제거
1. 데이터에서 결측치가 있는 데이터(행)를 모두 제거하시오.
2.결측치가 제거된 데이터를 사용하여 앞에서부터 70% 데이터를 구하시오. (단, 데이터 70% 지점의 index가 소수점으로 계산될 경우 소수점 이하는 버림)
3. 앞에서 구한 70%데이터 중 views 컬럼의 3사분위수에서 1사분위수를 뺀 값을 정수로 구하시오.

In [19]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('type1_data1.csv')

#결측치 제거
df = df.dropna()

#70% 데이터 구하기
end = int(len(df) * 0.7)

#70%데이터 슬라이싱
df = df.iloc[:end]

#3사분위수 - 1사분위수
int(df['views'].quantile(0.75) - df['views'].quantile(0.25))

2771

# Section 12 결측치 처리, 최빈값, 데이터 개수
1. 결측치가 가장 많은 두 컬럼을 찾으시오.
2. 첫 번째로 결측치가 많은 컬럼에서 결측치가 있는 데이터(행)를 삭제하시오
3. 두 번째로 결측치가 많은 컬럼을 최빈값으로 대체하시오.
4. 'f3'컬럼의 'gold'값을 가진 데이터의 수를 정수형으로 구하시오.

In [20]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('type1_data1.csv')

# 결측치가 가장 많은 컬럼을 확인
# df.isnull().sum() # f1 31 f3 29

# 첫번쨰로 결측치가 많은 칼럼의 결측치 삭제
df = df.dropna(subset = ['f1']) # subset으로 해당 행 지정

# 두 번째로 결측치가 많은 컬럼 최빈값 대체
freq = df['f3'].mode()[0]
df['f3'] = df['f3'].fillna(freq)
#f3 컬럼의 gold값을 가진 데이터의 수
cond = df['f3'] == 'gold'

df = df[cond]

len(df['f3'])

63

# Section 13 결측 데이터 찾기, 필터링, 평균값
1. 'f1'컬럼에 결측치가 있는 데이터만 선택하시오.
2. 선택된 데이터에서 'age'컬럼의 평균값을 구하시오. (반올림 후 소수 첫째 자리까지 계산)

In [21]:
import pandas as pd
df = pd.read_csv('type1_data1.csv')

#결측치가 있는 데이터만 선택
cond = df['f1'].isnull()

df= df[cond]

#age 컬럼의 평균값
round(df['age'].mean(),1)

np.float64(53.6)

# Section 14 중복 데이터 제거, 값 변경, 데이터 개수
1. 중복 데이터를 제거하시오.
2. 'f3' 컬럼의 결측치는 0, 'silver'는 1, 'gold'는 2, 'vip'는 3으로 변환하시오.
3. 변환된 'f3'컬럼의 총합을 정수형으로 구하시오.

In [22]:
import pandas as pd
df = pd.read_csv('type1_data1.csv')

#중복 데이터 제거
df.drop_duplicates(inplace=True)

#'f3' 컬럼의 결측치 대체
import numpy as np
df['f3'] = df['f3'].replace(np.nan,0).replace('silver',1).replace('gold',2).replace('vip',3)

#f3컬럼의 총합
print(int(df['f3'].sum()))

167

<ipython-input-22-ece9d39d6cdc>:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['f3'] = df['f3'].replace(np.nan,0).replace('silver',1).replace('gold',2).replace('vip',3)

In [23]:
import pandas as pd
df = pd.read_csv('type1_data1.csv')

#중복 데이터 제거
df.drop_duplicates(inplace=True)

#'f3'컬럼의 결측치 대체
import numpy as np
dict_list = {np.nan:0, 'silver':1,'gold':2,'vip':3}
df['f3'] = df['f3'].replace(dict_list)

int(df['f3'].sum())

<ipython-input-23-708ea8a58b40>:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['f3'] = df['f3'].replace(dict_list)

167

# Section 15 컬럼 삭제, 행 단위 합계, 필터링

1. 주어진 데이터에서 문자 자료형 컬럼을 삭제하시오.
2. 숫자 자료형 컬럼의 결측치를 0으로 대체하시오.
3. 각 행의 합이 3000보다 큰 값의 개수를 정수로 구하시오. (각 행의 합: 'age' + 'f1' + 'f2' + 'f5' + 'views')

In [24]:
import pandas as pd
df = pd.read_csv('type1_data1.csv')
# 실제로 확인
# df.info()
# 주어진 데이터에서 문자 자료형 컬럼 삭제
df.drop(['id','city','f3','f4','subscribed'], axis=1, inplace=True)

#숫자 자료형 컬럼의 결측치 0으로 대체
df.fillna(0, inplace=True)

#각 행의 합이 3000보다 큰 값의 개수
cond = df.sum(axis=1) > 3000

len(df[cond])

88

In [25]:
#자료형이 object가 아닌 칼럼 선택
cols = df.select_dtypes(exclude='object').columns
df = df[cols]

#결측치 0으로 대체
df = df.fillna(0)

#행과 열 변경
df = df.T
sum(df.sum() > 3000)

88

# Section 16 이상치, IQR

1. 'views'컬럼의 1사분위수, 3사분위수 그리고 IQR을 계산하시오.
2. 이상치 조건에 맞는 데이터를 찾으시오. (이상치는 1사분위수 - IQR * 1.5 보다 작은 값과 3사분위수 + IQR * 1.5 보다 큰값)
3. 이상치 데이터의 views 컬럼 합을 정수로 구하시오.

In [26]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('type1_data1.csv')

#1사분위수
q1 = df['views'].quantile(.25)
#3사분위수
q3= df['views'].quantile(.75)
#값확인
print("Q1 :",q1)
print("Q3 :",q3)
#IQR
IQR = q3 - q1
print("IQR:",IQR)

#이상치 조건에 맞는 데이터를 찾기
cond = (df['views'] < q1 - IQR *1.5 ) | (df['views'] > q3 + IQR * 1.5)
df = df[cond] # 조건에 맞는 데이터 저장

#이상치 데이터의 합
print("Answer:",int(df['views'].sum()))

Q1 : 3031.0
Q3 : 8473.5
IQR: 5442.5
Answer: 77699

In [27]:
#describe()로 찾기
df.describe()

             age    f1       f2         f5         views
count   4.000000   3.0  4.00000   4.000000      4.000000
mean   44.750000  57.0  0.50000  46.726011  19424.750000
std    25.223997   7.0  0.57735  35.020549   1697.088954
min    22.000000  50.0  0.00000  13.049921  17421.000000
25%    24.250000  53.5  0.00000  18.359563  18709.500000
50%    42.000000  57.0  0.50000  46.857921  19364.000000
75%    62.500000  60.5  1.00000  75.224368  20079.250000
max    73.000000  64.0  1.00000  80.138280  21550.000000

#Section 17 이상치, 소수점 있는 데이터 찾기, 표준편차

1. 'views'컬럼의 표준편차를 구하시오.
2. 'age'컬럼의 이상치(소수점 나이, 음수 나이, 0살)를 제거하고, 'views' 컬럼의 표준편차를 구하시오.
3. 이상치 제거 전후의 'views' 컬럼의 표준편차를 더하여, 반올림 후 소수 둘째 자리까지 구하시오.

In [28]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('type1_data1.csv')

#'views'컬럼의 표준편차
std1 = df['views'].std()
print('std:',std1)

#이상치 조건
cond1 = df['age'] == round(df['age'],0) #정수 나이인지 확인
cond2 = df['age'] > 0 #음수나 0 이 아닌지 확인

#이상치 제거
df = df[cond1 & cond2]

std2 = df['views'].std()
#이상치 제거 후 views 컬럼의 표준편차
print("new_std:",std2)

# 이상치 제거 전후의 views 컬럼의 표준편차의 합 후 반올림
round(std1 + std2,2)

std: 4121.626455600414
new_std: 4175.681776173446

8297.31

# Section 18 데이터(행) 기준 평균값, 인덱싱

1. index '2001' 데이터(행)에서 평균보다 큰 값의 개수를 구하시오.
2. index '2003' 데이터(행)에서 평균보다 작은 값의 개수를 구하시오.
3. 두 개수를 더하시오.

In [29]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('type1_data2.csv', index_col = 'year')

# 2001데이터행에서 평균보다 큰값
m1 = df.loc[2001].mean()
cond1 = df.loc[2001] > m1
r1 = sum(cond1)
# 2003 데이터행에서 평균보다 작은 값
m2 = df.loc[2003].mean()
cond2 = df.loc[2003] < m2
r2 = sum(cond2)
#개수
r1 + r2

202

#Section 19 결측치(뒤의 값으로 대체), 그룹합
1. 결측치를 바로 뒤에 있는 값으로 대체하시오. (바로 뒤의 값도 결측치일 경우, 뒤에 있는 데이터 중 가장 가까운 값으로 대체)
2. city와 f2컬럼을 기준으로 그룹합을 계산하시오.
3. views값이 세 번째로 큰 city 이름을 구하시오.

In [30]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('type1_data1.csv')

#결측치 채우기
df = df.fillna(method='bfill') #bfill: 뒤에있는걸로 채우기, ffill: 앞에있는 걸로 채우기

#그룹합 계산
df = df.groupby(['city','f2']).sum(numeric_only=True).reset_index()

#내림차순 정렬
df = df.sort_values('views', ascending = False)
#세번쨰로 큰 값구하기
df.iloc[2]['city']

<ipython-input-30-ec52cd1335e1>:6: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='bfill') #bfill: 뒤에있는걸로 채우기, ffill: 앞에있는 걸로 채우기

'경기'

# Section 20 시계열 데이터, 월별 집계, 인덱스
1. 연도 구분 없이 월별로 숫자형 컬럼의 합을 구하시오.
2. 합계 중 'views'가 가장 작은 값을 가진 월을 정수로 구하시오.

In [31]:
import pandas as pd
df = pd.read_csv('type1_data1.csv')

#날짜로 대체
df['subscribed'] = pd.to_datetime(df['subscribed'])

#월 추출
df['month'] = df['subscribed'].dt.month

#월별 집계
df = df.groupby('month').sum(numeric_only=True)

#합계 중 views 가 가장 작은 값을 가진 월(정수)
int(df['views'].idxmin())

11

#Section 21 시간 간의 차이 계산(분), 필터링
1. 예상 도착 시간보다 늦게 도착한 건수를 구하시오.
2. 이 중 거리가 7km 이상인 데이터의 수를 정수로 구하시오.

In [32]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('delivery_time.csv')
#datetime 변환
df[['실제도착시간','예상도착시간']] = df[['실제도착시간','예상도착시간']].apply(pd.to_datetime) # pd.to_datetime은 한번에 list처리 불가

#시간 비교
cond = df['실제도착시간'] > df['예상도착시간']
df = df[cond]

#거리가 7km이상인 데이터의 수
cond2 = df['거리'] >= 7
len(df[cond2])

311

#Section 22 시간 간의 차이 계산(분), 그룹핑
1. 주문 시간과 실제 도착 시간의 차이를 분 단위로 계산하시오.
2. 앱 종류별로 평균 도착 시간(분)을 계산하시오.
3. 평균적으로 가장 빠른 앱 종류를 찾고, 해당 앱의 평균 도착 시간을 분으로 반올림하여 정수로 구하시오.

In [33]:
# 데이터 불러오기
import pandas as pd
df = pd.read_csv('delivery_time.csv')
#to datetime
df[['주문시간','실제도착시간']] = df[['주문시간','실제도착시간']].apply(pd.to_datetime)
#소요시간 계산
df['소요시간'] = (df['실제도착시간'] - df['주문시간']).dt.total_seconds() / 60 #분으로 계산
#종류별 평균도착시간
df = df.groupby('앱종류')['소요시간'].mean()
#답
print(df.idxmin(),round(df.min()))

배고팡 62

# Section 23 시간 간의 차이 계산(분), 비율
1. 각 결제 종류별로 실제 도착 시간이 예상 도착 시간보다 늦은 주문의 비율을 계산하시오.
2. 비율 중 가장 큰 값을 반올림하여 소수 둘째 자리까지 구하시오.

In [34]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('delivery_time.csv')

#pd.to_datetime
df[['실제도착시간','예상도착시간']] = df[['실제도착시간','예상도착시간']].apply(pd.to_datetime)

#조건설정
cond = df['실제도착시간'] > df['예상도착시간']

#지연여부 col 설정
df['지연여부'] = cond

#비율 계산
df = df.groupby('결제종류')['지연여부'].mean()

print("Answer:",round(df.max(),2))

Answer: 0.56

#Section 24 그룹핑, 값 찾기, 필터링

1. 사용자별 주문 거리의 합계가 50km 이상인 사람들의 결제 방식을 구하시오.
2. 이 결제 방식 중 가장 빈도가 높은 수를 구하시오.

In [35]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('delivery_time.csv')

#그룹핑
df2 = df.groupby('user')['거리'].sum()
#조건 설정
cond = df2 > 50
df2 = df2[cond]
#유저 추출
df = df[df['user'].isin(df2.index)]
df['결제종류'].value_counts()[0]

<ipython-input-35-48469447f877>:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['결제종류'].value_counts()[0]

np.int64(48)

#Section 25 시간 간의 차이 계산(일)
1. 각 사용자별로 첫 주문과 마지막 주문 사이의 시간 간격을 일 단위로 계산하시오.
2. 시간차가 0일인 사용자를 제외하고, 나머지 사용자들의 평균 시간 간격(일 단위)을 계산하시오.
3. 평균 시간 간격보다 긴 시간 간격을 가진 사용자의 수를 정수로 수하시오.

In [36]:
import pandas as pd
df = pd.read_csv('delivery_time.csv')

#datetime
df['주문시간'] = pd.to_datetime(df['주문시간'])

#첫주문 마지막 주문 추출
First_order = df.groupby('user')['주문시간'].min()
Last_order = df.groupby('user')['주문시간'].max()
#시간 간격 계산
gap =(Last_order - First_order).dt.days

#시간차 0일인 사용자 제외
cond = gap>0
gap =gap[cond]

#평균 시간 간격 계산
gap_mean = gap.mean()

#평균 시간 간격보다 긴 시간 간격을 가진 사용자의 수
len(gap[gap > gap_mean])

146

# Section 26 날짜와 시간 정보 변환, 비율
1. 주문이 가장 많이 발생한 연-월을 찾으시오.
2. 해당 연-월에 '배고팡'앱을 통한 주문 중 '앱결제'로 결제된 주문의 비율을 계산하시오, (반올림 후 소수 둘째 자리까지 계산)

In [37]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('delivery_time.csv')

#Datetime
df['주문시간'] = pd.to_datetime(df['주문시간'])
#연-월 변환
df['주문시간'] = df['주문시간'].dt.to_period('M')

#가장 주문 많이 발생한 월 구하기
year_month = df['주문시간'].value_counts().idxmax()

## 조건 설정 ##

# 해당 연-월
cond1= df['주문시간'] == year_month

# 배고팡 앱
cond2 = df['앱종류'] == '배고팡'

# 조건 적용
filtered_data = df[cond1 & cond2].copy() # copy사용하여 오류 방지

# 앱결제로 결제된 주문
filtered_data['앱결제유무'] = filtered_data['결제종류'] == '앱결제'


#답 구하기
round(filtered_data['앱결제유무'].mean(),2)

np.float64(0.31)

# Section 27 시간 범위, 속도(km/h)
1. 점심시간(10시부터 13시 전까지)에 주문된 배달 데이터를 찾으시오.
2. 점심시간 주문 건 중 과속(평균 속도가 50km/h 이상)하는 주문 수를 정수로 구하시오.
  - 배달시간 = 실제도착시간 - 주문시간
  - 속도(km/h) = 거리(km)/ 시간(h)

In [38]:
# 데이터 불러오기
import pandas as pd
df = pd.read_csv('delivery_time.csv')

# pd.to_datetime
df[['주문시간','실제도착시간']] = df[['주문시간', '실제도착시간']].apply(pd.to_datetime)

#hour로 변환
# df['주문시간'] = df['주문시간'].dt.hour << 새로운 col로 대치해야함. 이런식 나중에 실제도착시간과 연산이 안됨

#hour로 조건 설정 후 점신시간 데이터로 제한
cond = (df['주문시간'].dt.hour >=10) & (df['주문시간'].dt.hour < 13)
df = df[cond]

#배달시간 구하기
df['배달시간'] = df['실제도착시간'] - df['주문시간']

#배달시간을 h단위로 변환
df['배달시간'] = df['배달시간'].dt.total_seconds()/60/60

#속도 계산
df['속도'] = df['거리'] / df['배달시간']

#속도가 50km/h이상인 수를 정수로 구하기
cond2 = df['속도'] > 50
df = df[cond2]

len(df)

1

# Section 28 날짜와 시간, 문자열

1. 연도와 월을 기준으로 주문 수를 집계하시오.
2. 가장 많은 주문이 있었던 연도와 월을 예시와 같은 형식으로 숫자로만 구하시오. (예: 2024년 2월인 경우 '202402', 2024년 10월인 경우 '202410')

In [39]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('delivery_time.csv')

#연도와 월 추출
df['주문시간'] = df['주문시간'].apply(pd.to_datetime)
df['주문시간'] = df['주문시간'].dt.to_period('M')

#가장 많은 주문이 있었던 연도와 월 추출
df = df.groupby('주문시간').size()

#문자열 변환 후 지정형식설정
most = str(df.idxmax()).replace('-','')
most

'202209'

# Section 29 함수, 월별 집계

1. 배달료 계산 기준표에 따라 각 주문에 대한 배달료를 계산하시오.
2. 월별로 배달료의 총합을 집계하시오.
3. 배달료가 가장 많이 발생한 월을 찾고, 그 월의 총 배달료를 정수로 구하시오.

[배달료 기준표]
- 5km 미만: 2,000원
- 5km 이상 ~ 10km 미만: 4,000원
- 10km 이상 ~ 15km 미만: 6,000원
- 15km 이상 ~ 20km 미만: 8,000원

In [40]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('delivery_time.csv')

#배달료 계산 함수 지정
def delivery_fee(x):
  if x < 5:
    return 2000
  elif x<10:
    return 4000
  elif x<15:
    return 6000
  else:
    return 8000

#배달료 col 추가
df['배달료'] = df['거리'].apply(delivery_fee)

#datetime 변환
df['주문시간'] = pd.to_datetime(df['주문시간'])

#월별로 주문시간 변환
df['주문시간'] = df['주문시간'].dt.to_period('M')

#월별 배달료 총합 집계
df = df.groupby('주문시간')['배달료'].sum()

#배달료가 가장 많은 달 선택
best_month = df.idxmax()

#총 배달료 정수 출력
int(df[best_month])

448000

# Section 30 주말, 평일 구분

1. 주말 주문 건수와 평일 주문 건수를 구하시오.
2. 주말 주문 건수와 평일 주문 건수의 차이를 절대값으로 구하고 정수형으로 구하시오.

In [41]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('delivery_time.csv')

#datetime
df['주문시간'] = pd.to_datetime(df['주문시간'])

#dayofweek
df['요일'] = df['주문시간'].dt.dayofweek

#평일 조건
cond1 = df['요일'] <= 4

#주말 조건
cond2 = df['요일'] > 4

#평일 주문 수
weekend = len(df[cond1])

#주말 주문 수
week = len(df[cond2])

#주문건수 차이
int(abs(weekend - week))

412

# Section 31 문자열, 형 변환
1. 'user' 컬럼에서 user 뒤에 있는 숫자 값만 추출하시오.
2. 추출된 숫자 값을 모두 합한 값을 정수로 구하시오.

In [42]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('delivery_time.csv')

#user column에서 숫자만 추출
df['user'] = df['user'].str[5:]

#추출된 숫자값을 모두 합하여 정수로변환
df['user'] = df['user'].astype('int') # int라 하는게 더 나을듯

#답 추출
df['user'].sum()

np.int64(261387)

# Section 32 합계(열 방향), 상위 값 선택
1. 수학, 영어, 국어 점수의 합을 구하시오.
2. 합이 가장 큰 상위 10명을 찾으시오.
3. 찾은 10명의 수학 평균 점수를 구하시오. (반올림 후 정수 출력)

In [43]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('school_data.csv')

#수학,영어,국어 점수의 합
df['합계'] = df['수학'] + df['영어'] + df['국어'] #결측치 처리 불가
# df['합계'] = df[['수학', '영어', '국어']]. #sum(axis = 1) 과 같은 답, 결측치 있을때 더 유리

#상위 10명
top10 = df['합계'].nlargest(10).index

#10명의 수학 평균 점수 구하기
top10_mean_math = df.loc[top10,'수학'].mean()

#Answer
int(round(top10_mean_math, 0))

82

# Section 33 데이터프레임 재구조화
1. 과목에 상관없이 점수가 가장 작은 점수 25개를 찾으시오.
2. 찾은 점수 25개의 합을 정수로 구하시오.

In [44]:
# 데이터 불러오기
import pandas as pd
df = pd.read_csv('school_data.csv')

#melting
melted_df = df.melt(id_vars='이름', value_vars=['수학','영어','국어'], var_name = '과목', value_name = '점수')

#가장 작은 점수 25개
low_scores = melted_df['점수'].nsmallest(25)
sum(low_scores)

420

# Section 34 데이터 합치기(concat)

1. 주어진 두 csv 파일(school_data,csv와 school_data_science.csv)을 학생 순서를 기준으로 병합하시오. (단, 두 파일의 학생 순서는 동일하다)

2. 학생별로 수학, 영어, 국어, 과학 점수의 평균을 구하시오.
3. 평균 점수가 60점 이상인 인원 수를 계산하시오.

In [47]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('school_data.csv')
df_science = pd. read_csv('school_data_science.csv')

#데이터 병합(학생 순서 기준)
df = pd.concat([df, df_science], axis = 1) #열을 기준으로 합침

#평균계산
df['수영국과평균'] = df[['수학', '영어','국어', '과학']].mean(axis=1)

#평균 점수가 60점 이상인 인원 수
cond = df['수영국과평균'] >= 60
df = df[cond]

len(df)

9

# Section 35 데이터 합치기(merge)

1. school_data.csv와 school_data_social.csv 파일을 '이름'을 기준으로 합치시오
2. 영어교사가 장선생이면서 사회교사가 오선생인 학생들을 필터링하시오.
3. 필터링된 학생들의 수학 점수를 모두 더한 후 정수로 구하시오.

In [6]:
#데이터 불러오기
import pandas as pd
df = pd.read_csv('school_data.csv')
df_social = pd.read_csv('school_data_social.csv')

# df 와 df_social의 순번이 다른것을 확인

# 이름을 기준으로 병합(merge)
df = pd.merge(df, df_social, on='이름')

#영어교사가 장선생인 조건
cond1 =  df['영어교사'] == '장선생'

#사회교사가 오선생인 조건
cond2 = df['사회교사'] == '오선생'

#필터링
df = df[cond1 & cond2]

#필터링된 학생들의 수학 점수 총합(정수)
int(df['수학'].sum())

602

# Section 36 조건별 변환(transform)

1. 결측된 판매금액은 해당 지역의 평균 판매금액으로 결측값을 대체하시오.
2. 각 거래마다 '판매금액'과 해당 지역의 평균 판매금액의 '차이'를 절대값으로 구하시오.
3. 각 지역에서 차이값의 평균을 구한 후, 이 값이 가장 큰 지역의 지역코드를 구하시오.

In [8]:
# 데이터 불러오기
import pandas as pd
df = pd.read_csv('sales.csv')

df

FileNotFoundError: [Errno 2] No such file or directory: 'sales.csv'